### ISSUE TITLE
Node.js version

### ISSUE THREAD

**Issue by jcubic** [sveltejs/svelte-cli#12]
Which version of Node is required, I have version v4.2.6 and I have error:

```
/usr/local/lib/node_modules/svelte-cli/bin.js:610
        const { sourceMap } = options;
              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by jcubic** [comment]
Switch to v6.9.4 from nvm and it's working.

**Comment by Rich-Harris** [comment]
FWIW we intend to get Node 4 support working — there's an issue for it here https://github.com/sveltejs/svelte/issues/109
