### ISSUE TITLE
Unexpected token `{` issue

### ISSUE THREAD

**Issue by radutopala** [sveltejs/svelte-cli#3]
```
svelte --help
/usr/local/lib/node_modules/svelte-cli/bin.js:607
	const { sourceMap } = options;
	      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by radutopala** [comment]
Closing, it was due to older nodejs version.

**Comment by atefBB** [comment]
Hey!
I upgrade npm/node but still have this error : 
![dfdfd](https://cloud.githubusercontent.com/assets/10966925/21159526/d6b80374-c181-11e6-8bc2-b74db6031f6b.png)
Any ideas?

**Comment by Ryuno-Ki** [comment]
@atefBB A good start would be to tell, what Node version do you use ;-)

`node --version`
